"""addee year to Talk model

Revision ID: 42410bd32a0f
Revises: 0040b49dd900
Create Date: 2018-04-15 21:03:02.515921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42410bd32a0f'
down_revision = '0040b49dd900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('talk', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('talk', 'year')
    # ### end Alembic commands ###
