"""Update talk model to add more data

Revision ID: 0040b49dd900
Revises: b31c07f1b9a2
Create Date: 2018-04-15 20:20:32.095074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0040b49dd900'
down_revision = 'b31c07f1b9a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('talk', sa.Column('location', sa.String(), nullable=True))
    op.add_column('talk', sa.Column('talk_dt', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('talk', 'talk_dt')
    op.drop_column('talk', 'location')
    # ### end Alembic commands ###
